services:
  db:
    image: postgres:15-alpine
    container_name: fintech-db
    restart: always
    environment:
      - POSTGRES_USER=lucas
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fintech_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: fintech-pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=lucas@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8081:80"
    depends_on:
      - db
